### ISSUE TITLE
CI with travis

### ISSUE THREAD

**Issue by portlek** [BananaPuncher714/NBTEditor#10]
Can we add Travis that can test the library with unit tests? It makes the project more stable/safe.

**Comment by BONNe** [comment]
Well, it could be enough just to create UnitTest. 
Jenkins build server will show if tests fails or not.

**Comment by portlek** [comment]
Alright, I will create test classes now?

**Comment by BananaPuncher714** [comment]
Yes, that's fine. I'll get around to doing it sometime, but you can feel free to submit another PR if you want.
