### ISSUE TITLE
Discussion about Unit Test.

### ISSUE THREAD

**Issue by portlek** [BananaPuncher714/NBTEditor#13]
I saw that we probably can't use a real unit test with Jupiter because we don't have NMS classes so, maybe we can make a `do-test.sh` shell script that can download BuildTools.jar and set up a temp. server in `test` directory and then it can run a class that can test the project.

What do you think about that?

**Comment by BananaPuncher714** [comment]
Github actions can be used to unit test, I think. [This](https://github.com/Derongan/NmsAction) action can be used to build a server and then run tests somehow.

**Comment by portlek** [comment]
> Github actions can be used to unit test, I think. [This](https://github.com/Derongan/NmsAction) action can be used to build a server and then run tests somehow.

Alright nice, I will try to make an action script with that.

**Comment by portlek** [comment]
I finished the unit testing with github action here;
https://github.com/forkstuffs/NBTEditor
![image](https://user-images.githubusercontent.com/12835420/86070898-79cbba00-ba86-11ea-9b96-5f32fdbf2572.png)

**Comment by BananaPuncher714** [comment]
Wouldn't it be possible to compile a jar with the test classes separately, instead of keeping the plugin inside the main directory?

**Comment by portlek** [comment]
> Wouldn't it be possible to compile a jar with the test classes separately, instead of keeping the plugin inside the main directory?

I will add a profile that allows us to don't put plugin.yml and NBEditorTestPlugin.java class, so it's possible with this design. But with test directory, nope I think it's not possible.

**Comment by portlek** [comment]
Ok done there are 2 profiles called test and maven.
mvn clean package -Ptest is for including plugin.yml and Test classes.
mvn clean package -Pmaven is for excluding plugin.yml and Test classes.
So, you just need to use `mvn clean deploy -Pmaven` to deploy the maven central.

**Comment by portlek** [comment]
You can look at my p.r. that can create server and run.
https://github.com/BananaPuncher714/NBTEditor/blob/7327e646a6e5ef0950863a0d698cffbed816a0e1/.github/workflows/maven.yml
@BananaPuncher714

**Comment by BananaPuncher714** [comment]
I tried that, but it gave me errors when it couldn't find the server jar. There is no other way to grab it without building it afaik.

I've been testing it on a [separate branch](https://github.com/BananaPuncher714/NBTEditor/tree/unit-testing), and this is what I'm planning on going with, unless you can improve it more. The workflow can be found [here](https://github.com/BananaPuncher714/NBTEditor/actions/runs/153068215)

This solution doesn't require having to create different profiles, nor does it involve putting test code in the main packages.

**Comment by BONNe** [comment]
Well, if you do it as UnitTest and use powerful powermock and mockito it is possible to do it in test directory without the necessity of server files (at least I think so).

But it would work well with Jenkins server. I do not know how it will like GitHub actions as they do not like external libraries very well. 

I once tried with a simple spigot dependency and it did not work.

**Comment by BananaPuncher714** [comment]
I'm not too sure about how well it would work, since NBTEditor does use reflection to access a lot of nms classes that wouldn't otherwise be accessible without the actual server.

**Comment by portlek** [comment]
Just merge my p.r. @BananaPuncher714  its working well.

**Comment by portlek** [comment]
> I tried that, but it gave me errors when it couldn't find the server jar. There is no other way to grab it without building it afaik.
> 
> I've been testing it on a [separate branch](https://github.com/BananaPuncher714/NBTEditor/tree/unit-testing), and this is what I'm planning on going with, unless you can improve it more. The workflow can be found [here](https://github.com/BananaPuncher714/NBTEditor/actions/runs/153068215)
> 
> This solution doesn't require having to create different profiles, nor does it involve putting test code in the main packages.

Alright, don't merge the unittest branch into master unless we make more tests.
