### ISSUE TITLE
Deep design thoughts.

### ISSUE THREAD

**Issue by portlek** [BananaPuncher714/NBTEditor#15]
I think the usage design is terrible for newbie developer: We should make it more understandable, for example;
```java
NBTEditor.of(itemStack).getCompound();
NBTEditor.of(itemStack).setCompound(compond);
```
Just an example. Also this design is more OOP so, we can understand how we can use the library or what the library behavior is. We have to look at the parameter name to understand how the library works, But I think we should add more understandable codes like above.

**Comment by BananaPuncher714** [comment]
I'd be fine with something like that as long as it doesn't require constraining the user. Although, do note that no matter what, setting anything on an item would require re-assigning it, so making a wrapper of an ItemStack may turn out more tedious especially if the user is only changing one or two things. If you're able to show more examples on how it would be implemented, I'd be glad to look over them.

**Comment by portlek** [comment]
> I'd be fine with something like that as long as it doesn't require constraining the user. Although, do note that no matter what, setting anything on an item would require re-assigning it, so making a wrapper of an ItemStack may turn out more tedious especially if the user is only changing one or two things. If you're able to show more examples on how it would be implemented, I'd be glad to look over them.

I will make a p.r. about that ASAP.

**Comment by portlek** [comment]
But first off all, we should add all tests. We can think the design after that.

**Comment by portlek** [comment]
Anyway I can't use the library because of the design and I can't write well-organized tests, I will change design first.

**Comment by portlek** [comment]
I'm making my own overhaul-design here;
https://github.com/forkstuffs/NBTEditor/blob/improvetests/src/main/java/io/github/bananapuncher714/nbteditor/NBTEditorNew.java

**Comment by portlek** [comment]
The new reflection design is finished, here;
https://github.com/forkstuffs/NBTEditor/blob/improvetests/src/main/java/io/github/bananapuncher714/nbteditor/util/Reflections.java

**Comment by BananaPuncher714** [comment]
I see. The reflection design does look a bit cleaner. But please note that one of the goals of NBTEditor was to be contained in a single class, for easy copy and paste purposes.

**Comment by portlek** [comment]
> I see. The reflection design does look a bit cleaner. But please note that one of the goals of NBTEditor was to be contained in a single class, for easy copy and paste purposes.

Yes, I will combine all classes into a single class, I'm making like that because this way is easier than writing in a single class.
