### ISSUE TITLE
Nonnull Can't be imported

### ISSUE THREAD

**Issue by iiTProductions** [BananaPuncher714/NBTEditor#16]
When i installed this Resource i have an error 

Error:(1313, 33) java: cannot find symbol
  symbol:   class Nonnull
  location: class me.iitproductions.unbreakable.NBTEditor.NBTCompound

**Comment by BananaPuncher714** [comment]
Ok, thanks. I'll see what I can do about it.

**Comment by BananaPuncher714** [comment]
Also, are you using the latest version?

**Comment by iiTProductions** [comment]
Its 1.12 project

**Comment by iiTProductions** [comment]
just installed so its probs the lastest version

**Comment by BananaPuncher714** [comment]
Ok, it should be fixed with the latest version(7.16.1). Thanks for reporting this!

**Comment by BananaPuncher714** [comment]
I'm going to close this unless it's still an issue.
