### ISSUE TITLE
It doesn't work for 1.18.2

### ISSUE THREAD

**Issue by Iseason2000** [BananaPuncher714/NBTEditor#20]
#### Example code

``` kotlin
val nbtCompound = NBTEditor.getNBTCompound(item)
nbtCompound.set(item, cost, "tag", "RepairCost")
return NBTEditor.getItemFromTag(nbtCompound)
```

#### Result:
![image](https://user-images.githubusercontent.com/65019366/156892580-55f1991f-d2d2-475e-9f16-a3684dccf16e.png)
 
------
#### Example code
``` kotlin
NBTEditor.contains(item, "RepairCost")
```
#### Result:
return false for every ItemStack

------
#### Example Code

``` kotlin 
NBTEditor.set(item, 6, "RepairCost")
```

**Comment by BananaPuncher714** [comment]
Thanks, I'll take a look when I get the chance.
