### ISSUE TITLE
NBTEditor appears to be affected by Paper relocation change

### ISSUE THREAD

**Issue by wouterdedroog** [BananaPuncher714/NBTEditor#34]
After testing out my plugin to see if it works after this change: https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/ I noticed that I'm getting errors from NBTEditor. I use the following code to test:
```
ItemStack stack = event.getPlayer().getItemInHand();
stack = NBTEditor.set(stack, "test", "customtag");
event.getPlayer().getInventory().addItem(stack);```

And get a stacktrace that tells me that the error is on the NBTEditor.set(..) line.

**Comment by BananaPuncher714** [comment]
Thanks, I'll see what I can do.
