### ISSUE TITLE
Maven support?

### ISSUE THREAD

**Issue by portlek** [BananaPuncher714/NBTEditor#6]

**Comment by BananaPuncher714** [comment]
I've considered it, but I don't have any place to host the repository. I've tried to host it directly on github, but it didn't work out for me. I'll try again if I can find somewhere else.

**Comment by portlek** [comment]
You can store it in the sonatype(maven central) it's free and simple to deploying.

**Comment by BananaPuncher714** [comment]
Ok, thank you. I did not know that before. I'll look into it and hopefully upload it soon.

**Comment by BONNe** [comment]
You can also contact with codemc.org. They have public maven repo for minecraft projects :)

**Comment by BananaPuncher714** [comment]
Maven support has been added with Github Packages.

**Comment by portlek** [comment]
GitHub Packages is not useful actually. Could we upload to maven-central?

**Comment by BananaPuncher714** [comment]
I've added NBTEditor to the CodeMC Maven repository. I'll update the README and other sources when I have time. As for Maven central, I'm hesitant about that since NBTEditor currently requires Spigot in the local repository.

```xml
<repository>
    <id>CodeMC</id>
    <url>https://repo.codemc.org/repository/maven-public</url>
</repository>
```

**Comment by portlek** [comment]
It doesn't matter, you can use NMS with that repository;
```xml
<repository>
    <id>nms-repo</id>
    <url>https://repo.codemc.org/repository/nms/</url>
</repository>
<dependency>
    <groupId>org.spigotmc</groupId>
    <artifactId>spigot</artifactId>
    <version>1.15.2-R0.1-SNAPSHOT</version>
    <scope>provided</scope>
</dependency>
```

**Comment by BananaPuncher714** [comment]
Sure, I'll take another look when I have time and see what stuff I need before uploading.
